apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: setsriovdefaultstopod-scc-hostnetwork-use
  namespace: set-sriov-defaults-to-pod
rules:
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    verbs:
      - use
    resourceNames:
      - hostnetwork
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: setsriovdefaultstopod-scc-hostnetwork-use
  namespace: set-sriov-defaults-to-pod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: setsriovdefaultstopod-scc-hostnetwork-use
subjects:
  - kind: ServiceAccount
    namespace: set-sriov-defaults-to-pod
    name: setsriovdefaultstopod
