apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: set-sriov-defaults-to-pod
  name: setsriovdefaultstopod
  labels:
    setsriovdefaultstopod: "true"
spec:
  selector:
    matchLabels:
      setsriovdefaultstopod: "true"
  template:
    metadata:
      name: setsriovdefaultstopod
      labels:
        setsriovdefaultstopod: "true"
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ''
      hostNetwork: true
      serviceAccountName: setsriovdefaultstopod
      containers:
        - name: setsriovdefaultstopod
          image: quay.io/itsoiref/sriov-webhook:latest
          imagePullPolicy: Always
          command:
            - /usr/bin/set-sriov-defaults-to-pod
          args:
            - "--secure-port=9448"
            - "--audit-log-path=-"
            - "--tls-cert-file=/var/serving-cert/tls.crt"
            - "--tls-private-key-file=/var/serving-cert/tls.key"
            - "--v=8"
          env:
            - name: CONFIGURATION_PATH
              value: /etc/setsriovdefaultstopod/config/override.yaml
          ports:
            - containerPort: 9448
              hostPort: 9448
              protocol: TCP
          volumeMounts:
            - mountPath: /var/serving-cert
              name: serving-cert
          readinessProbe:
            httpGet:
              path: /healthz
              port: 9448
              scheme: HTTPS
      volumes:
        - name: serving-cert
          secret:
            defaultMode: 420
            secretName: server-serving-cert
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 120
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 120
